### ISSUE TITLE
CDK issue

### ISSUE THREAD

**Issue by rgieseke** [chadvoegele/textadept-mac#2]
Just a quick note:

$(cdk_objs): %.o: cdk/%.c

needs to be changed to 

$(cdk_objs): cdk-%.o: cdk/%.c

I think

**Comment by chadvoegele** [comment]
You are right about the change. However, it was already in the patch. Maybe it did not apply cleanly for you?

In any case, I just made some updates for Textadept 10 compatibility.

Thanks for testing!

**Comment by rgieseke** [comment]
I think there was one missing 'cdk' which is now in - and it compiles with the latest beta, many thanks!

https://github.com/chadvoegele/textadept-mac/blob/master/build.patch#L46

With the cross-compile check this might be ready for submitting to Mitchell!

**Comment by chadvoegele** [comment]
Hi Robert,

I don't have access to a Mac anymore but I'll try to take a look at this
when I do again!

Thanks!
Chad
